defaults:
  - audio_htsat.yaml
  - text_roberta.yaml
  - _self_

mlp_loss: false
loss_weights: [1.0, 1.0]

fusion:
  enable: true
  type: aff_2d # aff_2d, aff_1d, iaff_2d, iaff_1d, daf_2d, daf_1d

batch_size: 128
optimizer:
  method: Adam
  kwargs: 
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1e-8
    momentum: null

lr_scheduler:
  method: cosinelr
  warmup_epochs: 3
  # method: steplr
  # step_size: 40
  # gamma: 0.1

### split-opt ####
# split_optimiezr: False
# optimizer_new:
#   method: Adam
#   kwargs: 
#     lr: 0.0001
#     betas: [0.9, 0.999]
#     eps: 1e-8
#     momentum: null
# optimizer_pretrained:
#   method: Adam
#   kwargs: 
#     lr: 0.0001
#     betas: [0.9, 0.999]
#     eps: 1e-8
#     momentum: null