# @package _global_

defaults:
  - override /data: default-spatial-all.yaml 
  - _self_

datamodule:
  _target_: data.datamodule.DataModule

modelmodule:
  _target_: model.model_module.sCLAPModelModule

model:
  batch_size: 64
  audio:
    seld_method: EINV2
    ckpt_path: # [seld_path, clap_path]
      - ckpts/EINV2-HTSAT-0.514.ckpt
      - ckpts/CLAP/630k-audioset-fusion-best.pt
      # - null
  text:
    ckpt_path: ckpts/CLAP/630k-audioset-fusion-best.pt

trainer:
  max_epochs: 10

task: spatial-retrieval