# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - hydra: default.yaml
  - logger: tensorboard.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - paths: default.yaml
  - data: default.yaml
  - model: default.yaml
  - extras: default.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - task: retrieval.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task/experiment name, determines output directory path
task_name: ${task}
experiment_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}

num_workers: 16

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 2025

# compile model for faster training with pytorch 2.0
compile: True